create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null default '',
  category text not null,
  variant text not null,
  unit text not null default 'piece',
  price_paise integer not null check (price_paise >= 0),
  stock integer not null default 0 check (stock >= 0),
  low_stock_at integer not null default 5 check (low_stock_at >= 0),
  aliases text not null default '',
  image_url text not null default '',
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  unique(name, variant)
);
create index if not exists products_search_idx on public.products using gin (to_tsvector('simple', name || ' ' || brand || ' ' || category || ' ' || variant || ' ' || aliases));

create table if not exists public.carts (
  id text primary key,
  status text not null default 'active' check (status in ('active','ordered','abandoned')),
  updated_at timestamptz not null default now()
);
create table if not exists public.cart_items (
  cart_id text not null references public.carts(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null check (quantity > 0),
  primary key(cart_id, product_id)
);
create table if not exists public.orders (
  id text primary key,
  cart_id text not null,
  fulfillment text not null check (fulfillment in ('delivery','pickup')),
  payment_method text not null check (payment_method in ('cod','online')),
  payment_status text not null default 'pending',
  order_status text not null default 'confirmed',
  subtotal_paise integer not null,
  delivery_paise integer not null default 0,
  total_paise integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.orders add column if not exists delivery_address text not null default '';
create table if not exists public.order_items (
  id bigint generated always as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  product_id bigint not null,
  name text not null,
  variant text not null,
  quantity integer not null,
  price_paise integer not null
);
create table if not exists public.inventory_movements (
  id bigint generated always as identity primary key,
  product_id bigint not null,
  delta integer not null,
  reason text not null,
  reference_id text,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.inventory_movements enable row level security;

create or replace function public.search_shop_products(search_text text)
returns setof public.products language sql stable security definer set search_path=public as $$
  select * from public.products
  where active=true and (
    search_text is null or trim(search_text)='' or
    lower(name || ' ' || brand || ' ' || category || ' ' || variant || ' ' || aliases) like '%' || lower(trim(search_text)) || '%'
  ) order by name, variant limit 100;
$$;

create or replace function public.set_shop_cart_item(p_cart_id text, p_product_id bigint, p_quantity integer)
returns void language plpgsql security definer set search_path=public as $$
declare available integer;
begin
  if length(p_cart_id) < 8 or p_quantity < 0 or p_quantity > 99 then raise exception 'INVALID_CART_UPDATE'; end if;
  insert into carts(id) values(p_cart_id) on conflict(id) do nothing;
  if p_quantity=0 then delete from cart_items where cart_id=p_cart_id and product_id=p_product_id; return; end if;
  select stock into available from products where id=p_product_id and active=true for update;
  if available is null then raise exception 'PRODUCT_NOT_AVAILABLE'; end if;
  if p_quantity > available then raise exception 'ONLY_%_AVAILABLE', available; end if;
  insert into cart_items(cart_id,product_id,quantity) values(p_cart_id,p_product_id,p_quantity)
    on conflict(cart_id,product_id) do update set quantity=excluded.quantity;
  update carts set updated_at=now() where id=p_cart_id;
end; $$;

drop function if exists public.place_shop_order(text,text,text);
create or replace function public.place_shop_order(p_cart_id text, p_fulfillment text, p_payment_method text, p_address text default '')
returns text language plpgsql security definer set search_path=public as $$
declare new_id text := 'MM-' || upper(substr(md5(random()::text || clock_timestamp()::text),1,10)); subtotal integer; delivery integer;
declare line record;
begin
  if p_fulfillment not in ('delivery','pickup') or p_payment_method not in ('cod','online') then raise exception 'INVALID_CHECKOUT'; end if;
  if p_fulfillment='delivery' and trim(coalesce(p_address,''))='' then raise exception 'DELIVERY_ADDRESS_REQUIRED'; end if;
  select coalesce(sum(ci.quantity*p.price_paise),0) into subtotal from cart_items ci join products p on p.id=ci.product_id where ci.cart_id=p_cart_id;
  if subtotal=0 then raise exception 'CART_EMPTY'; end if;
  for line in select ci.product_id,ci.quantity,p.stock,p.name,p.variant,p.price_paise from cart_items ci join products p on p.id=ci.product_id where ci.cart_id=p_cart_id for update of p loop
    if line.quantity > line.stock then raise exception 'OUT_OF_STOCK: %', line.name; end if;
    update products set stock=stock-line.quantity,updated_at=now() where id=line.product_id;
    insert into inventory_movements(product_id,delta,reason,reference_id) values(line.product_id,-line.quantity,'order',new_id);
  end loop;
  delivery := case when p_fulfillment='delivery' and subtotal<50000 then 4000 else 0 end;
  insert into orders(id,cart_id,fulfillment,payment_method,payment_status,subtotal_paise,delivery_paise,total_paise,delivery_address)
    values(new_id,p_cart_id,p_fulfillment,p_payment_method,case when p_payment_method='cod' then 'cod_pending' else 'payment_link_pending' end,subtotal,delivery,subtotal+delivery,case when p_fulfillment='delivery' then trim(p_address) else '' end);
  insert into order_items(order_id,product_id,name,variant,quantity,price_paise)
    select new_id,ci.product_id,p.name,p.variant,ci.quantity,p.price_paise from cart_items ci join products p on p.id=ci.product_id where ci.cart_id=p_cart_id;
  update carts set status='ordered',updated_at=now() where id=p_cart_id;
  return new_id;
end; $$;

revoke all on table public.products, public.carts, public.cart_items, public.orders, public.order_items, public.inventory_movements from anon, authenticated;
revoke execute on function public.search_shop_products(text) from public, anon, authenticated;
revoke execute on function public.set_shop_cart_item(text,bigint,integer) from public, anon, authenticated;
revoke execute on function public.place_shop_order(text,text,text,text) from public, anon, authenticated;
grant usage on schema public to service_role;
grant all on table public.products, public.carts, public.cart_items, public.orders, public.order_items, public.inventory_movements to service_role;
grant usage, select on sequence public.products_id_seq, public.order_items_id_seq, public.inventory_movements_id_seq to service_role;
grant execute on function public.search_shop_products(text) to service_role;
grant execute on function public.set_shop_cart_item(text,bigint,integer) to service_role;
grant execute on function public.place_shop_order(text,text,text,text) to service_role;

insert into public.products(name,brand,category,variant,unit,price_paise,stock,low_stock_at,aliases,image_url) values
('Colgate Strong Teeth','Colgate','Toothpaste','100 g','tube',6800,24,5,'coldgate,కోల్గేట్,कोलगेट,tooth paste','https://images.unsplash.com/photo-1609840114035-3c981b782dfe?auto=format&fit=crop&w=400&q=80'),
('Colgate Strong Teeth','Colgate','Toothpaste','200 g','tube',12200,12,5,'coldgate,కోల్గేట్,कोलगेट,big colgate','https://images.unsplash.com/photo-1609840114035-3c981b782dfe?auto=format&fit=crop&w=400&q=80'),
('Santoor Sandal Soap','Santoor','Bath soap','100 g','piece',4200,18,5,'santor,సంతూర్,संतूर,soap','https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=400&q=80'),
('Santoor Sandal Soap','Santoor','Bath soap','100 g × 4','pack',15600,8,5,'santoor pack,సంతూర్ ప్యాక్,संतूर पैक','https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=400&q=80'),
('Aashirvaad Atta','Aashirvaad','Groceries','5 kg','bag',29500,10,5,'atta,flour,గోధుమ పిండి,आटा','https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80'),
('Tata Salt','Tata','Groceries','1 kg','packet',2800,30,5,'salt,ఉప్పు,नमक','https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=400&q=80'),
('Parle-G Biscuits','Parle','Snacks','800 g','pack',8500,16,5,'parleg,biscuit,బిస్కెట్,बिस्कुट','https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80'),
('Surf Excel Easy Wash','Surf Excel','Laundry','1 kg','packet',15400,6,5,'surf,detergent,సర్ఫ్,डिटर्जेंट','https://images.unsplash.com/photo-1583947581924-860bda6a26df?auto=format&fit=crop&w=400&q=80')
on conflict(name,variant) do nothing;

-- Keep multilingual discovery terms up to date without overwriting owner-managed
-- price, stock, images, or active state when this migration is rerun.
update public.products set aliases='coldgate,కోల్గేట్,పేస్ట్,టూత్‌పేస్ట్,कोलगेट,टूथपेस्ट,मंजन,tooth paste'
where name='Colgate Strong Teeth' and variant='100 g';
update public.products set aliases='coldgate,కోల్గేట్,పేస్ట్,టూత్‌పేస్ట్,कोलगेट,टूथपेस्ट,मंजन,big colgate'
where name='Colgate Strong Teeth' and variant='200 g';
update public.products set aliases='santor,సంతూర్,సబ్బు,संतूर,साबुन,soap'
where name='Santoor Sandal Soap' and variant='100 g';
update public.products set aliases='santoor pack,సంతూర్ ప్యాక్,సబ్బు ప్యాక్,संतूर पैक,साबुन पैक,soap pack'
where name='Santoor Sandal Soap' and variant='100 g × 4';
